### ISSUE TITLE
Issue about 0.31 release

### ISSUE THREAD

**Issue by Kyle-Ye** [migueldeicaza/SwiftGodotBinary#2]
1. When we update the binary url, in most cases we should also update the checksum.
https://github.com/migueldeicaza/SwiftGodotBinary/commit/d4c5611e42a4ed70be2f63898fc582f479bba62e

2. The xcframework is fine if we download, unzip it manually and consume it via Xcode. But it will not work if we are using SwiftPM.

SwiftPM will use `unzip -d xx yy` internally and no input can be added. However the xcframework for 0.30 and 0.31 will both having issue if we unzip it this way.

The error message is something similar to the following which corresponding to https://github.com/apple/swift-package-manager/blob/a5771ec467f9d552a4e78f05814f207f258693f6/Sources/Workspace/Diagnostics.swift#L159
```
failed extracting 'https://github.com/migueldeicaza/SwiftGodot/releases/download/0.31/SwiftGodot.xcframework.zip' which is required by binary target 'SwiftGodot': replace /xxx/SwiftGodotBinary-gviarpfpgonnuohbsbvphnzkozqg/SourcePackages/artifacts/extract/swiftgodotbinary/SwiftGodot/E1D71214-A29F-4904-AD18-C02F5AF7DA6E/SwiftGodot.xcframework/macos-arm64_x86_64/SwiftGodot.framework/Resources? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
```

And you can reproduce it by running the following command.
```
wget https://github.com/migueldeicaza/SwiftGodot/releases/download/0.31/SwiftGodot.xcframework.zip
unzip -d . ./SwiftGodot.xcframework.zip

// requiring inputs from user
// ❌ Throw an error in SwiftPM
replace ./SwiftGodot.xcframework/macos-arm64_x86_64/SwiftGodot.framework/Resources? [y]es, [n]o, [A]ll, [N]one, [r]ename:
```

**Comment by migueldeicaza** [comment]
My script to publish this was supposed to do this, but it looks like there is a bug in the script, as it has not been updated the file for a few iterations, going to debug this.

**Comment by migueldeicaza** [comment]
Can you try again, this should be fixed

**Comment by Kyle-Ye** [comment]
No. It still doesn't seem to be fixed. The this error message for 0.32.

Could you help reopen this?

Env: 
- macOS 14.1.2 (23B92)
- Xcode Version 15.0 (15A240d)
- Zip 3.0 Compiled with gcc Apple LLVM 15.0.0 (clang-1500.0.37.1) [+internal-os] for Unix (Mac OS X) on Sep 30 2023.

Reproduce step:
```
git clone git@github.com:migueldeicaza/SwiftGodotBinary.git
cd SwiftGodotBinary
swift build

Downloading binary artifact https://github.com/migueldeicaza/SwiftGodot/releases/download/0.32/SwiftGodot.xcframework.zip
error: failed extracting 'https://github.com/migueldeicaza/SwiftGodot/releases/download/0.32/SwiftGodot.xcframework.zip' which is required by binary target 'SwiftGodot': replace <private>/SwiftGodotBinary/.build/artifacts/extract/swiftgodotbinary/SwiftGodot/A074CB8E-70E8-4DCF-A28C-F6DCA2788797/SwiftGodot.xcframework/macos-arm64_x86_64/SwiftGodot.framework/Resources? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
(EOF or read error, treating as "[N]one" ...)
```

**Comment by Kyle-Ye** [comment]
Can we add a CI to check it? I can do this if you are welcome for it. See #3

Also I'd like to suggest we release a same version tag here so that downstream user can use
`.package(url: "https://github.com/migueldeicaza/SwiftGodotBinary", from: "0.3.2")` or `exact: "0.3.2"` instead of `branch: "main"`

**Comment by migueldeicaza** [comment]
I do not mind the CI check, but this is not the source of this problem.

I downloaded the 0.32 and 0.34 releases, and they both have the correct checksums now, I believe we are dealing with a different problem.   The zip error that you point out seems to be caused by something else, I noticed this on the zip file:

```
armpro$ unzip -v SwiftGodot.xcframework.zip  | grep macos-arm64_x86_64/SwiftGodot.framework/Resources
       0  Stored        0   0% 10-16-2023 16:07 00000000  SwiftGodot.xcframework/macos-arm64_x86_64/SwiftGodot.framework/Resources/
    1269  Defl:N      448  65% 10-16-2023 16:07 cba6edee  SwiftGodot.xcframework/macos-arm64_x86_64/SwiftGodot.framework/Resources/Info.plist
      26  Stored       26   0% 12-09-2023 20:07 8702472c  SwiftGodot.xcframework/macos-arm64_x86_64/SwiftGodot.framework/Resources
```

It looks like the first entry includes a directory, and the second a file with the same name.

**Comment by migueldeicaza** [comment]
I think the issue is the packaging of the XCFramework as a zip files that uses --symlink.

Without --symlinks it increases the size by 46 megs (130 to 146).

If I use the finder to compress, the package becomes even smaller and does not produce this error.

So I would love to figure out what Finder is doing.

**Comment by migueldeicaza** [comment]
Replacing zip with ditto seems to do it:

ditto -c -k --sequesterRsrc --keepParent SwiftGodot.xcframework archive.zip

**Comment by Kyle-Ye** [comment]
Still have issue with 0.35 and we did not update the checksum.
```
unzip -d ./ ./SwiftGodot.xcframework.zip
Archive:  ./SwiftGodot.xcframework.zip
   creating: ./SwiftGodot.xcframework/
   creating: ./SwiftGodot.xcframework/macos-arm64_x86_64/
   creating: ./SwiftGodot.xcframework/macos-arm64_x86_64/SwiftGodot.framework/
  inflating: ./SwiftGodot.xcframework/macos-arm64_x86_64/SwiftGodot.framework/SwiftGodot
   creating: ./SwiftGodot.xcframework/macos-arm64_x86_64/SwiftGodot.framework/Resources/
  inflating: ./SwiftGodot.xcframework/macos-arm64_x86_64/SwiftGodot.framework/Resources/Info.plist
   creating: ./SwiftGodot.xcframework/macos-arm64_x86_64/SwiftGodot.framework/Versions/
   creating: ./SwiftGodot.xcframework/macos-arm64_x86_64/SwiftGodot.framework/Versions/A/
  inflating: ./SwiftGodot.xcframework/macos-arm64_x86_64/SwiftGodot.framework/Versions/A/SwiftGodot
   creating: ./SwiftGodot.xcframework/macos-arm64_x86_64/SwiftGodot.framework/Versions/A/Resources/
  inflating: ./SwiftGodot.xcframework/macos-arm64_x86_64/SwiftGodot.framework/Versions/A/Resources/Info.plist
   creating: ./SwiftGodot.xcframework/macos-arm64_x86_64/SwiftGodot.framework/Versions/Current/
  inflating: ./SwiftGodot.xcframework/macos-arm64_x86_64/SwiftGodot.framework/Versions/Current/SwiftGodot
   creating: ./SwiftGodot.xcframework/macos-arm64_x86_64/SwiftGodot.framework/Versions/Current/Resources/
  inflating: ./SwiftGodot.xcframework/macos-arm64_x86_64/SwiftGodot.framework/Versions/Current/Resources/Info.plist
   creating: ./SwiftGodot.xcframework/macos-arm64_x86_64/SwiftGodot.framework/Versions/Current/Headers/
  inflating: ./SwiftGodot.xcframework/macos-arm64_x86_64/SwiftGodot.framework/Versions/Current/Headers/SwiftGodot-Swift.h
  inflating: ./SwiftGodot.xcframework/macos-arm64_x86_64/SwiftGodot.framework/Versions/Current/Headers/SwiftGodot.h
   creating: ./SwiftGodot.xcframework/macos-arm64_x86_64/SwiftGodot.framework/Versions/Current/Modules/
   creating: ./SwiftGodot.xcframework/macos-arm64_x86_64/SwiftGodot.framework/Versions/Current/Modules/SwiftGodot.swiftmodule/
  inflating: ./SwiftGodot.xcframework/macos-arm64_x86_64/SwiftGodot.framework/Versions/Current/Modules/SwiftGodot.swiftmodule/arm64-apple-macos.swiftdoc
  inflating: ./SwiftGodot.xcframework/macos-arm64_x86_64/SwiftGodot.framework/Versions/Current/Modules/SwiftGodot.swiftmodule/x86_64-apple-macos.swiftdoc
  inflating: ./SwiftGodot.xcframework/macos-arm64_x86_64/SwiftGodot.framework/Versions/Current/Modules/SwiftGodot.swiftmodule/arm64-apple-macos.swiftmodule
   creating: ./SwiftGodot.xcframework/macos-arm64_x86_64/SwiftGodot.framework/Versions/Current/Modules/SwiftGodot.swiftmodule/Project/
  inflating: ./SwiftGodot.xcframework/macos-arm64_x86_64/SwiftGodot.framework/Versions/Current/Modules/SwiftGodot.swiftmodule/Project/x86_64-apple-macos.swiftsourceinfo
  inflating: ./SwiftGodot.xcframework/macos-arm64_x86_64/SwiftGodot.framework/Versions/Current/Modules/SwiftGodot.swiftmodule/Project/arm64-apple-macos.swiftsourceinfo
  inflating: ./SwiftGodot.xcframework/macos-arm64_x86_64/SwiftGodot.framework/Versions/Current/Modules/SwiftGodot.swiftmodule/arm64-apple-macos.abi.json
  inflating: ./SwiftGodot.xcframework/macos-arm64_x86_64/SwiftGodot.framework/Versions/Current/Modules/SwiftGodot.swiftmodule/x86_64-apple-macos.abi.json
  inflating: ./SwiftGodot.xcframework/macos-arm64_x86_64/SwiftGodot.framework/Versions/Current/Modules/SwiftGodot.swiftmodule/x86_64-apple-macos.swiftmodule
  inflating: ./SwiftGodot.xcframework/macos-arm64_x86_64/SwiftGodot.framework/Versions/Current/Modules/module.modulemap
    linking: ./SwiftGodot.xcframework/macos-arm64_x86_64/SwiftGodot.framework/Headers  -> Versions/Current/Headers
    linking: ./SwiftGodot.xcframework/macos-arm64_x86_64/SwiftGodot.framework/Modules  -> Versions/Current/Modules
   creating: ./SwiftGodot.xcframework/ios-arm64/
   creating: ./SwiftGodot.xcframework/ios-arm64/SwiftGodot.framework/
  inflating: ./SwiftGodot.xcframework/ios-arm64/SwiftGodot.framework/SwiftGodot
   creating: ./SwiftGodot.xcframework/ios-arm64/SwiftGodot.framework/Versions/
   creating: ./SwiftGodot.xcframework/ios-arm64/SwiftGodot.framework/Versions/Current/
   creating: ./SwiftGodot.xcframework/ios-arm64/SwiftGodot.framework/Versions/Current/Headers/
  inflating: ./SwiftGodot.xcframework/ios-arm64/SwiftGodot.framework/Versions/Current/Headers/SwiftGodot-Swift.h
   creating: ./SwiftGodot.xcframework/ios-arm64/SwiftGodot.framework/Versions/Current/Modules/
   creating: ./SwiftGodot.xcframework/ios-arm64/SwiftGodot.framework/Versions/Current/Modules/SwiftGodot.swiftmodule/
  inflating: ./SwiftGodot.xcframework/ios-arm64/SwiftGodot.framework/Versions/Current/Modules/SwiftGodot.swiftmodule/arm64-apple-ios.swiftdoc
   creating: ./SwiftGodot.xcframework/ios-arm64/SwiftGodot.framework/Versions/Current/Modules/SwiftGodot.swiftmodule/Project/
  inflating: ./SwiftGodot.xcframework/ios-arm64/SwiftGodot.framework/Versions/Current/Modules/SwiftGodot.swiftmodule/Project/arm64-apple-ios.swiftsourceinfo
  inflating: ./SwiftGodot.xcframework/ios-arm64/SwiftGodot.framework/Versions/Current/Modules/SwiftGodot.swiftmodule/arm64-apple-ios.swiftmodule
  inflating: ./SwiftGodot.xcframework/ios-arm64/SwiftGodot.framework/Versions/Current/Modules/SwiftGodot.swiftmodule/arm64-apple-ios.abi.json
  inflating: ./SwiftGodot.xcframework/ios-arm64/SwiftGodot.framework/Versions/Current/Modules/module.modulemap
    linking: ./SwiftGodot.xcframework/ios-arm64/SwiftGodot.framework/Headers  -> Versions/Current/Headers
    linking: ./SwiftGodot.xcframework/ios-arm64/SwiftGodot.framework/Modules  -> Versions/Current/Modules
  inflating: ./SwiftGodot.xcframework/ios-arm64/SwiftGodot.framework/Info.plist
  inflating: ./SwiftGodot.xcframework/Info.plist
replace ./SwiftGodot.xcframework/macos-arm64_x86_64/SwiftGodot.framework/Resources? [y]es, [n]o, [A]ll, [N]one, [r]ename:
```
